name = "bing-wallpapers-worker"
main = "index.js"
compatibility_date = "2025-08-02"

local_protocol = "http"
local_port = 8787

kv_namespaces = [
  { binding = "BING_KV", id = "your-kv-namespace-id" }
]
[vars]
IMPORT_PASSWORD = "super_secret"