name: Daily Bing Import

on:
  schedule:
    - cron: '30 2 * * *'  # 每天 UTC+0 02:30 执行（北京时间 10:30）
  workflow_dispatch:      # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Debug directory structure
        run: |
          ls -la
          
      - name: Run import script
        run: |
          python daily_import.py
